export enum ComponentType {
  RootDependencyInjector = "root_dependency_injector",
  DependencyInjector = "dependency_injector",
  Controller = "controller",
  ControllerUnitTest = "controller_unit_test",
  DataSource = "data_source",
  DataSourceUnitTest = "data_source_unit_test",
  Endpoint = "endpoint",
  Entity = "entity",
  EntityUnitTest = "entity_unit_test",
  Enum = "enum",
  Ioc = "ioc",
  Input = "input",
  InputUnitTest = "input_unit_test",
  Mapper = "mapper",
  MapperUnitTest = "mapper_unit_test",
  Model = "model",
  Output = "output",
  OutputUnitTest = "output_unit_test",
  QueryBuilder = "query_builder",
  QueryBuilderUnitTest = "query_builder_unit_test",
  Repository = "repository",
  RepositoryImpl = "repository_impl",
  RepositoryFactory = "repository_factory",
  RepositoryFactoryUnitTest = "repository_factory_unit_test",
  RepositoryImplUnitTest = "repository_impl_unit_test",
  Route = "route",
  RouteUnitTest = "route_unit_test",
  Schema = "schema",
  Service = "service",
  ServiceImpl = "service_impl",
  ServiceFactory = "service_factory",
  ServiceFactoryUnitTest = "service_factory_unit_test",
  ServiceImplUnitTest = "service_impl_unit_test",
  UseCase = "use_case",
  UseCaseUnitTest = "use_case_unit_test",
  Util = "util",
}

export enum WriteMethod {
  Skip = "skip",
  Overwrite = "overwrite",
  Patch = "patch",
}

export enum ModelType {
  Json = "json",
  Mongo = "mongo",
  Redis = "redis",
}
